import { createHash } from "node:crypto";
import type {
  AtlasSymbol,
  ConfidenceBand,
  LanguageId,
  RelationKind,
  Relationship,
  SourceLocation,
  SymbolKind,
} from "../../../core/src/types/index.js";

export interface ParseResult {
  symbols: AtlasSymbol[];
  relationships: Relationship[];
  language: LanguageId;
}

export interface LanguageAdapter {
  id: LanguageId;
  extensions: string[];
  parse(filePath: string, source: string): ParseResult;
}

export function hashContent(source: string): string {
  return createHash("sha256").update(source).digest("hex").slice(0, 16);
}

export function symbolId(
  file: string,
  kind: SymbolKind,
  name: string,
  line: number,
): string {
  const norm = file.replace(/\\/g, "/");
  return createHash("sha1")
    .update(`${norm}|${kind}|${name}|${line}`)
    .digest("hex")
    .slice(0, 16);
}

export function relId(
  kind: RelationKind,
  fromId: string,
  toId: string,
): string {
  return createHash("sha1")
    .update(`${kind}|${fromId}|${toId}`)
    .digest("hex")
    .slice(0, 16);
}

export function bandFor(confidence: number): ConfidenceBand {
  if (confidence >= 0.95) return "STATIC";
  if (confidence >= 0.8) return "HIGH";
  if (confidence >= 0.55) return "MEDIUM";
  return "LOW";
}

export function makeSymbol(opts: {
  file: string;
  name: string;
  kind: SymbolKind;
  language: LanguageId;
  line: number;
  column?: number;
  endLine?: number;
  qualifiedName?: string;
  signature?: string;
  exported?: boolean;
  entryPoint?: boolean;
  generated?: boolean;
  metadata?: Record<string, unknown>;
  contentHash?: string;
}): AtlasSymbol {
  const id = symbolId(opts.file, opts.kind, opts.name, opts.line);
  return {
    id,
    name: opts.name,
    qualifiedName: opts.qualifiedName ?? opts.name,
    kind: opts.kind,
    language: opts.language,
    location: {
      file: opts.file.replace(/\\/g, "/"),
      line: opts.line,
      column: opts.column,
      endLine: opts.endLine,
    },
    signature: opts.signature,
    exported: opts.exported,
    entryPoint: opts.entryPoint,
    generated: opts.generated,
    contentHash: opts.contentHash,
    metadata: opts.metadata,
  };
}

export function makeRel(opts: {
  kind: RelationKind;
  fromId: string;
  toId: string;
  confidence: number;
  location?: SourceLocation;
  evidence?: string;
}): Relationship {
  return {
    id: relId(opts.kind, opts.fromId, opts.toId),
    kind: opts.kind,
    fromId: opts.fromId,
    toId: opts.toId,
    confidence: opts.confidence,
    band: bandFor(opts.confidence),
    location: opts.location,
    evidence: opts.evidence,
  };
}

export function lineNumberAt(source: string, index: number): number {
  let line = 1;
  for (let i = 0; i < index && i < source.length; i++) {
    if (source[i] === "\n") line++;
  }
  return line;
}

export function isGeneratedFile(filePath: string, source: string): boolean {
  const norm = filePath.replace(/\\/g, "/").toLowerCase();
  if (
    norm.includes("/generated/") ||
    norm.includes("/gen/") ||
    norm.endsWith(".g.ts") ||
    norm.endsWith(".generated.ts") ||
    norm.endsWith(".pb.go") ||
    norm.endsWith("_generated.go") ||
    norm.endsWith(".g.dart")
  ) {
    return true;
  }
  const head = source.slice(0, 400).toLowerCase();
  return (
    head.includes("code generated") ||
    head.includes("auto-generated") ||
    head.includes("autogenerated") ||
    head.includes("@generated") ||
    head.includes("do not edit")
  );
}

export function detectLanguage(filePath: string): LanguageId {
  const ext = filePath.split(".").pop()?.toLowerCase();
  switch (ext) {
    case "ts":
    case "tsx":
    case "mts":
    case "cts":
      return "typescript";
    case "js":
    case "jsx":
    case "mjs":
    case "cjs":
      return "javascript";
    case "py":
      return "python";
    case "go":
      return "go";
    case "rs":
      return "rust";
    case "rb":
      return "ruby";
    case "dart":
      return "dart";
    case "cs":
      return "csharp";
    case "java":
      return "java";
    default:
      return "unknown";
  }
}

/** Resolve a simple name against symbols in the same file / imports. */
export function resolveNameToSymbol(
  name: string,
  candidates: AtlasSymbol[],
): AtlasSymbol | undefined {
  const exact = candidates.find(
    (s) => s.name === name || s.qualifiedName === name || s.qualifiedName.endsWith(`.${name}`),
  );
  return exact;
}
